queue_rules:
  - name: dependency-updates
    batch_size: 5
    batch_max_wait_time: 10 min
    checks_timeout: auto
    merge_method: merge-batch
    queue_conditions:
      - base = main
      - author ~= ^(dependabot|renovate|lockfile-maintenance)\[bot\]$
      - -draft
      - -conflict
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - check-success = actionlint & zizmor
    merge_conditions:
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - check-success = actionlint & zizmor

merge_protections_settings:
  auto_merge_conditions:
    - base = main
    - author ~= ^(dependabot|renovate|lockfile-maintenance)\[bot\]$
    - -draft
    - -conflict
    - "#approved-reviews-by >= 1"
    - "#changes-requested-reviews-by = 0"
  reporting_method: check-runs
