name: "Update Tools"

description: |
  Update a version of a given tool listed in .tool-versions

inputs:
  tool:
    type: string
    required: true
  constraint:
    type: string
    default: ""
    required: false
  labels:
    type: string
    default: "dependencies"
    required: false
  release_url:
    type: string
    default: ""
    required: false
  token:
    type: string
    required: false
    default: "${{ github.token }}"

outputs:
  current_version:
    description: The current version
    value: ${{ steps.versions.outputs.current_version }}
  latest_version:
    description: The latest version found
    value: ${{ steps.versions.outputs.latest_version }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Install tools via mise
      uses: jdx/mise-action@v2
      with:
        install: false

    - id: versions
      name: Get the current and latest versions of the tool
      run: |
        tool="${{ inputs.tool }}"
        constraint="${{ inputs.constraint }}"

        mise plugins install "$tool" || :

        CURRENT_VERSION=$(mise current "$tool")
        LATEST_VERSION=$(mise latest "$tool" ${constraint:+"${constraint}"})

        tee -a "$GITHUB_ENV" <<EOF
        CURRENT_VERSION=$CURRENT_VERSION
        LATEST_VERSION=$LATEST_VERSION
        EOF

        tee -a "$GITHUB_OUTPUT" <<EOF
        current_version=$CURRENT_VERSION
        latest_version=$LATEST_VERSION
        EOF
      shell: bash

    - name: Install the latest version and update .tool-versions
      if: ${{ env.LATEST_VERSION != env.CURRENT_VERSION }}
      run: |
        mise local "${{ inputs.tool }}" "${{ env.LATEST_VERSION }}"
      shell: bash

    - name: Prepare information for PR
      if: ${{ env.LATEST_VERSION != env.CURRENT_VERSION }}
      run: |
        RELEASE_URL="${{ inputs.release_url }}"
        if [ -z "$RELEASE_URL" ]; then
          q="\"${{ inputs.tool }} ${{ env.LATEST_VERSION }}\" release"
          RELEASE_URL="https://www.google.com/search?q=$(jq -rn --arg q "$q" '$q|@uri')"
        fi
        tee -a "$GITHUB_ENV" <<EOF
        RELEASE_URL=$RELEASE_URL
        EOF
      shell: bash

    - uses: peter-evans/create-pull-request@v5
      if: ${{ env.LATEST_VERSION != env.CURRENT_VERSION }}
      with:
        token: "${{ inputs.token }}"
        add-paths: .tool-versions
        commit-message: "Update ${{ inputs.tool }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}"
        title: "Update ${{ inputs.tool }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}"
        body: |
          Updates ${{ inputs.tool }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}.

          ${{ env.RELEASE_URL }}
        branch: "update_tools/${{ inputs.tool }}/${{ inputs.constraint }}"
        delete-branch: true
        labels: "${{ inputs.labels }}"
